import type { Product } from './api';

/**
 * Liste statique utilisée si l'API est injoignable ou si la base n'a pas
 * encore été seedée. Les slugs correspondent à ceux du seed, donc un clic
 * sur une carte fonctionne si le backend est démarré après l'affichage
 * initial.
 */
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'fallback-glow-skin',
    slug: 'glow-skin',
    name: 'Glow Skin Crème',
    category: 'Beauté',
    price: 24900,
    promo: 32000,
    stock: 42,
    image: '/products/glow-skin.png',
    description: "Hydratation intense, éclat visible en 7 jours. Soin quotidien enrichi en huile d'argan, acide hyaluronique et vitamine E.",
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-trim-active',
    slug: 'trim-active',
    name: 'Trim Active Plus',
    category: 'Amincissant',
    price: 18500,
    promo: 0,
    stock: 35,
    image: '/products/trim-active.png',
    description: 'Programme silhouette 28 jours. Complexe drainant à base de plantes, formule non-stimulante.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-curve-up',
    slug: 'curve-up',
    name: 'Curve Up Gel',
    category: 'Postérieur',
    price: 27500,
    promo: 0,
    stock: 20,
    image: '/products/curve-up.png',
    description: 'Routine tonifiante et raffermissante. Gel à la caféine végétale et beurre de karité.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-confidence',
    slug: 'confidence',
    name: 'Confidence Kit',
    category: 'Promo',
    price: 54000,
    promo: 72000,
    stock: 12,
    image: '/products/confidence.png',
    description: 'Rituel complet beauté + silhouette. Coffret signature, 5 produits hero, livraison offerte.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-shape-mask',
    slug: 'shape-mask',
    name: 'Shape & Firm Masque',
    category: 'Postérieur',
    price: 19900,
    promo: 0,
    stock: 25,
    image: '/products/shape-mask.png',
    description: 'Masque raffermissant express 20 min. Intensif, à poser 2 fois par semaine.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-lip-glow',
    slug: 'lip-glow',
    name: 'Lip & Glow Set',
    category: 'Promo',
    price: 15900,
    promo: 22000,
    stock: 28,
    image: null,
    description: 'Pack découverte lèvres + visage. Baume lèvres teinté + huile visage illuminatrice.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-velvet-body',
    slug: 'velvet-body',
    name: 'Velvet Body Milk',
    category: 'Beauté',
    price: 12900,
    promo: 0,
    stock: 60,
    image: null,
    description: 'Lait corps soyeux karité + coco. Ultra-nourrissant, parfum fleur de coton.',
    status: 'PUBLISHED',
  },
  {
    id: 'fallback-slim-tea',
    slug: 'slim-tea',
    name: 'Slim Detox Tea',
    category: 'Amincissant',
    price: 9500,
    promo: 0,
    stock: 80,
    image: null,
    description: 'Infusion drainante 21 jours. Mélange artisanal de plantes, une infusion matin et soir.',
    status: 'PUBLISHED',
  },
];
